version: '3.6'
services:
  db:
    image: mysql
    hostname: localhost
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_USER: user
      MYSQL_PASSWORD: jupiter
      MYSQL_ROOT_PASSWORD: jupiter*
    ports:
      - 3306:3306